meilisearch/meilisearch-js-plugins

src/index.js
Partially fixes #15, especially this comment https://github.com/meilisearch/instant-meilisearch/issues/15#issuecomment-667811239.
=> Fix error when content is null

.github/workflows/test.yml, CONTRIBUTING.md, package.json, playgrounds/react/README.md, playgrounds/vue/README.md, playgrounds/vue/package.json
What do you think @bidoubiwa? Is the naming correct for the `scripts` in `package.json` file?
=> Add scripts in packages.json for demo tests

src/index.js
=> Propagate filters parameter to meilisearch

src/format.js
Reverts meilisearch/instant-meilisearch#82
=> Revert "Check highlight tags before replacing them"

examples/esm/package.json, examples/express/package.json
See https://github.com/meilisearch/instant-meilisearch/issues/125#issuecomment-724016925
=> Change License to MIT

src/index.js
=> Add attibutesToRetrieve

playgrounds/vue/yarn.lock
Fixes https://github.com/meilisearch/instant-meilisearch/compare/fix-security-alert2?expand=1
=> Update yarn.lock in playground/vue and fix security alert

playgrounds/html/package.json, playgrounds/html/yarn.lock
And update dependencies in `playgrounds/html/yarn.lock`
=> Fix node-forge vulnerability in playgrounds/html

.github/workflows/release-drafter.yml, .github/workflows/test.yml, CONTRIBUTING.md, README.md
=> Change master into main

package.json, yarn.lock
=> Update eslint-plugin-vue to 7.6.0

package.json, yarn.lock
to avoid merge conflict in #262
=> Update ts-jest to 26.5.1

package.json
=> Update to v0.3.1

playgrounds/react/src/App.css, playgrounds/react/src/App.js
Replace Hits with InfiniteHits in the React Playground & fix image style which were overflowing
=> Fix react playground

package.json
Fix infinite hits bug and changes distorted object in response body
=> update package to v0.4.0

jest.config.js, package.json, rollup.config.js, src/transformers/__tests__/pagination.tests.ts, yarn.lock
=> Add jest watch

src/adapter/to-instantsearch-highlight.ts
=> Avoid snippeting on empty string

package.json
Release body will be updated with specific explanation on breaking changes
=> Update to v0.5

src/types/types.ts, tests/assets/utils.ts, tests/facetsDistribution.tests.ts, tests/highlight.tests.ts, tests/pagination.tests.ts, tests/snippets.tests.ts
see #389 
Unit tests have also been added see: 
#387
=> Add snippet/highlight/pagination integration tests

playgrounds/html/README.md
=> Remove dead link

src/types/types.ts, tests/facets-distribution.tests.ts
Tests will fail until this is fixed: https://github.com/meilisearch/MeiliSearch/issues/1504
=> Update facets distribution

tests/snippets.tests.ts
Failing tests until  https://github.com/meilisearch/MeiliSearch/issues/1505 is adressed
=> Update snippet tests for v0.21

README.md
=> Fix compatibility with refinementList condition

README.md
Per @gmourier tests, these widgets are compatible provided that you meet the requirements. 
For example the document structure and the settings.
=> Add compatibility with hierarchicalMenu/breadcrumb/RatingsMenu in readme

package.json
=> Update version for the next release (v0.6.2)

tests/snippets.tests.ts
=> Test that ellipsis on smaller values than cropsize are not added

package.json, src/adapter/search-request-adapter/filters.ts, src/cache/first-facets-distribution.ts, src/contexts/search-context.ts, src/types/types.ts, yarn.lock
Update meilisearch-js to latest none-beta version
=> Update meilisearch-js to v0.27.0

README.md
=> fix links in Readme.md

.github/scripts/beta-docker-version.sh, .github/workflows/beta-tests.yml
Add automatic testing of the beta feature by gripping the correct docker image
=> Add beta testing in CI

src/cache/__tests__/search-cache.tests.ts
as per this comment https://github.com/meilisearch/instant-meilisearch/pull/727#discussion_r936076636
=> Remove redundant  words in tests description

package.json, src/package-version.ts
Bump the version for the incoming release
=> Update version for the next release (v0.8.2)

package.json, src/package-version.ts
=> Update version for the next release (v0.10.1)

package.json, yarn.lock
Add missing `turbo` dependency required to interact with the packages.
=> Add turbo as a dependency

README.md, packages/instant-meilisearch/README.md
=> Update the outdated meilisearch host in the README's

.changeset/curvy-ravens-walk.md, README.md, packages/instant-meilisearch/README.md, packages/instant-meilisearch/__tests__/custom-http-client.test.ts, packages/instant-meilisearch/__tests__/instantiation.test.ts, packages/instant-meilisearch/src/client/config/index.ts, packages/instant-meilisearch/src/client/instant-meilisearch-client.ts, packages/instant-meilisearch/src/types/types.ts
=> Provide the possibility to give your own httpClient and request configs

package.json, playgrounds/node-env/index.js
For some reason the node test is not running when trying to release. This seems to fix the issue
=> Fix the node tests in the CI

playgrounds/autocomplete/package.json
Makes autocomplete a public package and provides its first version
=> Create first public version for autocomplete client

packages/instant-meilisearch/package.json, yarn.lock
Update the meilisearch package to v0.34.0
=> Update meilisearch js to v0.34.0

.changeset/giant-clouds-smell.md, packages/instant-meilisearch/src/cache/__tests__/fill-missing-facets.test.ts, packages/instant-meilisearch/src/cache/init-facets-distribution.ts, packages/instant-meilisearch/src/client/instant-meilisearch-client.ts, playgrounds/local-react/src/components/MultiIndex.jsx, playgrounds/local-react/src/components/SingleMovieIndex.jsx, playgrounds/react/package.json, yarn.lock
Fixes #1040 
The `initialFacetDistribution` were missing the hierarchical facets we get from the search, which was breaking the `HierarchicalMenu`. 
This PR aims to fix it by adding `fillMissingFacets` function that is called at every search.
It also updates the React playground to `instant-search` v7.
=> Fix `HierarchicalMenu` when `keepZeroFacets` is set to true

CONTRIBUTING.md
- Update changeset section
- Remove `OMIT IN TOC` to fix local links
=> Improve CONTRIBUTING.md about changeset

.changeset/calm-beans-talk.md, packages/instant-meilisearch/CHANGELOG.md, packages/instant-meilisearch/package.json, packages/instant-meilisearch/src/package-version.ts, playgrounds/angular/package.json, playgrounds/geo-javascript/package.json, playgrounds/javascript/package.json, playgrounds/local-react/package.json, playgrounds/react/package.json, playgrounds/vue3-ts/package.json
Following #1272 this will make sure the changesets will work properly after merging this.
=> Fix version as 0.13.6 so changesets will update to next minor

.changeset/small-dolls-move.md, packages/instant-meilisearch/package.json, yarn.lock
Update meilisearch-js dependency version to fix #1299
=> Update meilisearch-js version to v0.40

.changeset/big-swans-cover.md, packages/instant-meilisearch/rollup.config.js
=> Fix wrong meilisearch client being imported in UMD bundle

.changeset/calm-snakes-dream.md, packages/autocomplete-client/rollup.config.js
=> Fix rollup importing wrong 'meilisearch' in auto-complete

.changeset/slimy-wombats-breathe.md, packages/instant-meilisearch/package.json, yarn.lock
This is part of the Meilisearch release v1.11 but I had to close that original PR #1325
=> Update meilisearch to v1.11

.changeset/plenty-peaches-lick.md
Add a changeset file to trigger a minor bump for `instant-meilisearch`
=> Add v1.12 changeset

.changeset/hip-adults-shout.md, packages/instant-meilisearch/package.json, yarn.lock
Update meilisearch-js to v0.47
=> bump meilisearch-js version to the latest available

packages/autocomplete-client/src/search/__tests__/fetchMeilisearchResults.test.ts, packages/instant-meilisearch/__tests__/configure.attributes-to-retrieve.test.ts, packages/instant-meilisearch/__tests__/custom-http-client.test.ts, packages/instant-meilisearch/__tests__/disjunctive-facet-search.test.ts, packages/instant-meilisearch/__tests__/facet-stats.test.ts, packages/instant-meilisearch/__tests__/facets-distribution.test.ts, packages/instant-meilisearch/__tests__/filter.test.ts, packages/instant-meilisearch/__tests__/first-facets-distribution.test.ts, packages/instant-meilisearch/__tests__/geosearch.test.ts, packages/instant-meilisearch/__tests__/highlight.test.ts, packages/instant-meilisearch/__tests__/instantiation.test.ts, packages/instant-meilisearch/__tests__/multi-index-search.test.ts, packages/instant-meilisearch/__tests__/overridden-meilisearch-parameters.test.ts, packages/instant-meilisearch/__tests__/pagination.test.ts, packages/instant-meilisearch/__tests__/placeholder-search.test.ts, packages/instant-meilisearch/__tests__/snippets.test.ts, packages/instant-meilisearch/__tests__/sort.test.ts, packages/instant-meilisearch/package.json, packages/instant-meilisearch/src/client/config/index.ts, packages/instant-meilisearch/src/client/instant-meilisearch-client.ts, packages/instant-meilisearch/src/types/types.ts, playgrounds/autocomplete/setup.mjs, playgrounds/local-react/setup.mjs, playgrounds/node-env/index.js, yarn.lock
- Bump meilisearch-js dependency to v0.50
=> Chore/bump meilisearch js to 0.50
