- README.md
- examples/express/tests/client.test.js
- playgrounds/vue/src/App.vue
- src/index.js
Closes #23 
Bonus: add custom parameters in the playground
> Add browse when no queries are entered

- README.md
- examples/express/tests/client.test.js
- package.json
- playgrounds/react/src/App.js
- playgrounds/vue/src/App.vue
- src/index.js
- tests/base.test.js
Why rename `limitPerRequest`? Because of the confusion: it's not a limit per request but the total (and finite) number of results you can browse during pagination. It fixes partially the confusion in #18.
Why remove `hitsPerPage`? Because we can already configure it with [`InstantSearch.configure`](https://www.algolia.com/doc/api-reference/widgets/configure/js/) function and our parameter would be redundant.
> Remove histPerPage and rename limitPerRequest into paginationTotalResults

- package.json
This should make a repository link appear e.g. on https://www.npmjs.com/package/@meilisearch/instant-meilisearch and make the github link on https://bundlephobia.com/result?p=@meilisearch/instant-meilisearch work.
> Add repository backlink for npm

- playgrounds/vanilla-js/package.json
- playgrounds/vanilla-js/yarn.lock
In vanilla-js playground: fix security vulnerability for node-forge and update yarn.lock dependencies.
> Fix security vulnerability for node-forge

- CONTRIBUTING.md
- playgrounds/html/public/index.html
- playgrounds/javascript/src/app.js
- playgrounds/react/src/App.js
- playgrounds/vue/src/App.vue
- rollup.config.js
- src/index.js
- tests/base.test.js
- tests/env/esm/src/index.js
- tests/env/node/index.js
Following the decision taken in `meilisearch-js`: https://github.com/meilisearch/meilisearch-js/pull/756
MeiliSearch Js decided to go in the direction of new best practices in JS libraries by changing from default export to named export.
ES:
```javascript
import {instantMeiliSearch } from '@meilisearch/instant-meilisearch' // ES
const searchClient = instantMeiliSearch(...);
``` 
Node
```javascript
const { instantMeiliSearch } = require('@meilisearch/instant-meilisearch') // Node
const searchClient = instantMeiliSearch(...);
``` 
```javascript
instantMeiliSearch // browser
window.instantMeiliSearch // browser
const searchClient = instantMeiliSearch(...);
const searchClient2 = window.instantMeiliSearch(...);
```
> Changed to named export instead of default export

- src/index.ts
`splice` became `slice` during the whole typescript process 🙃
> Fix slice function that broke pagination

- .github/workflows/test.yml
- playgrounds/angular/e2e/src/app.po.ts
Tests were failing when MeiliSearch instance did not respond fast enough. 
I added a wait for element to be sure we give meilisearch enough time.
> Make angular e2e tests more consistant

- README.md
- playgrounds/react/src/App.js
- src/index.ts
- src/types.ts
With the new version of `instantSearch`, `objectID` becomes mandatory in the hits information to avoid errors and warnings in the console.
For example, in `React` when using instant-meilisearch the following error is raised: 
```
react_devtools_backend.js:2430 Warning: Failed prop type: The prop `hits[0].objectID` is marked as required in `Hits`, but its value is `undefined`.
react_devtools_backend.js:2430 Warning: Each child in a list should have a unique "key" prop.
```
Because instantSearch adds the `objectID` as the key of every hit component, we both receive an error for its absence and an error because our components are missing a key prop as [react expects a key on every component](https://reactjs.org/docs/lists-and-keys.html#keys).
First I tried to fetch the primaryKey from …
> Add objectID when primaryKey is provided

- playgrounds/react/src/App.js
- src/index.ts
Processing time provided to instantSearch was badly formatted, as instantSearch expects `processingTimeMS` and we provided `processingTimeMs` as per MeiliSearch naming in its response.
> Fix processing time that was always 0 in Stats widget

- .eslintignore
- .gitignore
- README.md
- playgrounds/react/src/App.js
- src/index.ts
- src/types.ts
- tests/base.test.ts
- tests/env/express/tests/client.test.js
- tests/env/node/node.test.js
Fix `<InfiniteHits />` that did not work without `<Pagination />`
Refactor code a bit to make it more readable. 
Removed `attributesToHighlight` from client params as they were always equal to `['*']`. 
Also updated `transformToMeiliSearchParams` to fetch `attributesToHighlight` from `instantsearch.js`  to compare it with ours.
It is also never going to be used by `instantSearch` as it is not a requested option in a `SearchClient` (see below)
```javascript
export declare type SearchClient = {
addAlgoliaAgent?: (agent: string) => void;
search: (requests: SearchRequest[]) => Promise<{
results: SearchResponse[];
}>;
searchForFacetValues?: (requests: SearchForFacetValuesRequest[]) => Promise<{
facetHits: SearchForFacetValuesResponse[];
}[]>;
};
```
> Fix infinite hits

- src/format.ts
The body of _highlightedResult used to look like this:
The field should be transformed to String using `JSON.stringify` to keep all information. 
It looks like this with this fix.
> Fix nested object being transfom into [object, object] in highlight

- src/index.ts
Avoid this error on search 
```bash
MeiliSearchApiError: Can't perform facet count, as no facet is set
```
Fixes also hitsPerPage being ignored.
> Fix failing search on missing facets

- src/index.ts
See: https://github.com/meilisearch/meilisearch-vue/issues/21
Numeric filters were not added to instantsearch's filters field. 
Demo: https://codesandbox.io/s/meilisearch-boardgames-uj2tr?file=/src/App.vue
> Communicate filters and numeric filters properly to instantsearch

- tests/pagination.tests.ts
Fix pagination tests impacted by change in `id` hashing and thus results appear in another order
> Pagination tests

- README.md
- cypress/integration/search-ui.spec.js
- package.json
- playgrounds/angular/src/app/app.component.html
- playgrounds/angular/src/app/app.component.ts
- playgrounds/html/public/index.html
- playgrounds/javascript/index.html
- playgrounds/javascript/src/app.js
- playgrounds/react/src/App.js
- playgrounds/vue/src/App.vue
- src/adapter/to-meilisearch-params.ts
- src/client/index.ts
- src/types/types.ts
usage example: 
```js
<SortBy
defaultRefinement="steam-video-games"
items={[
{ value: 'steam-video-games', label: 'Relevant' },
{
value: 'steam-video-games:recommendationCount:asc',
label: 'Least Recommended',
},
{
value: 'steam-video-games:recommendationCount:desc',
label: 'Most Recommended',
},
{
value: 'steam-video-games-sort:recommendationCount:asc', // different index with different ranking rules
label: 'Relevant Least Recommended ',
},
{
value: 'steam-video-games-sort:recommendationCount:desc', // different index with different ranking rules
label: 'Relevant Most Recommended',
},
]}
/>
```
`value` attribute is  syntaxed the following way  `index:attributes:order`.
Both `query time` sorting and `indexing time sorting` are possible. Meaning, it is still possible, to add multiple …
> Add sort by widget compatibility

- src/adapter/highlight-adapter.ts
> fix highlight on non arrays

- .github/workflows/publish.yml
- .github/workflows/test.yml
- bors.toml
> Update ci versions

- src/adapter/search-response-adapter/highlight-adapter.ts
- tests/assets/utils.ts
- tests/highlight.tests.ts
- tests/snippets.tests.ts
> Fix error on non array/object/string being highlighted

- README.md
- src/adapter/search-request-adapter/__tests__/facets-distribution-assigns.tests.ts
- src/adapter/search-request-adapter/__tests__/filter-cache.tests.ts
- src/adapter/search-request-adapter/__tests__/search-params.tests.ts
- src/adapter/search-request-adapter/filters.ts
- src/adapter/search-request-adapter/search-resolver.ts
- src/adapter/search-response-adapter/pagination-adapter.ts
- src/adapter/search-response-adapter/search-response-adapter.ts
- src/cache/first-facets-distribution.ts
- src/cache/index.ts
- src/client/contexts.ts
- src/client/instant-meilisearch-client.ts
- src/types/types.ts
fixes: #599 
Some improvements were done on the readme as well
> Add possibility to show facets with 0 matching documents

- README.md
- jest.config.js
- package.json
- src/adapter/search-request-adapter/__tests__/search-params.tests.ts
- src/adapter/search-request-adapter/search-params-adapter.ts
- src/adapter/search-request-adapter/search-resolver.ts
- src/adapter/search-response-adapter/pagination-adapter.ts
- src/adapter/search-response-adapter/search-response-adapter.ts
- src/client/instant-meilisearch-client.ts
- src/contexts/index.ts
- src/contexts/pagination-context.ts
- src/contexts/search-context.ts
- src/types/types.ts
- tests/pagination.tests.ts
Fixes: #569 
fixes: #521 
By default instant-meilisearch used to fetch 200 documents on every search request. This was needed to ensure we can provide a finite pagination when the user used the `pagination` widget (with the 1, 2, 3, at the bottom of the screen). 
This impacted the speed of the search considerably. Indeed meilisearch is designed to retrieve the most relevant documents, but not all the relevant documents. The more you ask, the more the search engine has to process. There is no difference regarding the search time between retrieving 6 or 7 documents, but between 6 and 200 documents to every request, the impact can be huge.
It also impacted users using the `infiniteHits` widget as well while it is not necessary for them. The `infiniteHits` settings does not need to showcase a …
> Introduce finitePagination setting: remove default fetch of 200 documents

- README.md
- package.json
- src/client/instant-meilisearch-client.ts
- src/types/types.ts
- tests/assets/utils.ts
- tests/base.tests.ts
- tests/build.tests.js
- tests/configure.attributes-to-retrieve.tests.ts
- tests/facets-distribution.tests.ts
- tests/filter.tests.ts
- tests/geosearch.tests.ts
- tests/highlight.tests.ts
- tests/pagination.tests.ts
- tests/snippets.tests.ts
> Remove meilisearch client from public access

- package.json
- src/adapter/search-request-adapter/__tests__/search-params.tests.ts
- src/adapter/search-request-adapter/search-params-adapter.ts
- src/adapter/search-request-adapter/search-resolver.ts
- src/client/instant-meilisearch-client.ts
- src/contexts/search-context.ts
- src/types/types.ts
- tests/assets/utils.ts
- tests/base.tests.ts
- tests/build.tests.js
- tests/configure.attributes-to-retrieve.tests.ts
- tests/facets-distribution.tests.ts
- tests/filter.tests.ts
- tests/geosearch.tests.ts
- tests/highlight.tests.ts
- tests/pagination.tests.ts
- tests/placeholder-search.tests.ts
- tests/snippets.tests.ts
Fixes #709 
`placeholderSearch` is suppose to not showcase any search result when the query is empty. It now correctly does what it is suppose to do. It is also improved as it will now avoid to do a search request to Meilisearch.
> Fix placeholdersearch

- tests/configure.attributes-to-retrieve.tests.ts
- tests/filter.tests.ts
- tests/highlight.tests.ts
- tests/pagination.tests.ts
- tests/snippets.tests.ts
Changes have been made on the order in which the documents are ordered by default. Tests have been updated accordingly
See https://github.com/meilisearch/meilisearch/pull/2298 for more information
> Fix tests related to changes in placeholder hits order resolver

- package.json
This version makes this package compatible with Meilisearch v0.27.0 :tada:
Check out the changelog of [Meilisearch v0.27.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.27.0) for more information on the changes.
- Add highlight prefix suffix tags #739
- Add crop marker support #738
Thanks again to @bidoubiwa and @mmachatschek! 🎉
> Update version for the next release (v0.7.1)

- package.json
- yarn.lock
Update the meilisearch-js package version to the beta version currently compatible with [v0.28.0rc1](https://github.com/meilisearch/meilisearch/releases/tag/v0.28.0rc1)
> Bump meilisearch js to v0.27.0-beta.0

- src/adapter/search-request-adapter/filters.ts
- src/adapter/search-request-adapter/search-params-adapter.ts
- src/adapter/search-request-adapter/search-resolver.ts
- src/adapter/search-response-adapter/hits-adapter.ts
- src/adapter/search-response-adapter/search-response-adapter.ts
- src/cache/__tests__/assets/utils.ts
- src/cache/first-facets-distribution.ts
- src/client/instant-meilisearch-client.ts
- src/types/types.ts
- tests/configure.attributes-to-retrieve.tests.ts
- tests/env/react/setup.js
- tests/facets-distribution.tests.ts
- tests/filter.tests.ts
- tests/geosearch.tests.ts
- tests/highlight.tests.ts
- tests/pagination.tests.ts
- tests/placeholder-search.tests.ts
- tests/search-resolver.tests.ts
- tests/snippets.tests.ts
Applies the breaking changes from the new version of meilisearch-js see [`v0.27.0-beta.1` release](https://github.com/meilisearch/meilisearch-js/releases/tag/v0.27.0-beta.1)
⚠️ The `FacetsDistribution` type provided by `meilisearch-js` should be updated to `FacetDistribution`. This change will be present in the next beta version of the package
There are no breaking changes!
> Update search route request and response parameters naming v0.28.x

- package.json
- src/package-version.ts
This version makes this package compatible with Meilisearch v0.28.0 :tada:
Check out the changelog of [Meilisearch v0.28.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.28.0) for more information on the changes.
- `facetsDistribution` search request parameter was renamed to `facets` causing a throw when using this package version with a version of Meilisearch prior to [`v0.28.0rcX`](https://github.com/meilisearch/meilisearch/releases/tag/v0.28.0rc1). #779 
- This release is only compatible with the latest version of [Meilisearch v0.28.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.28.0)
- Pass client agent to meilisearch-js #780
Analytics is enabled by default in the server, but you can disable them by following [this …
> Update version for the next release (v0.8.0)

- README.md
- playgrounds/angular/src/app/app.component.ts
- playgrounds/geo-javascript/src/app.js
- playgrounds/html/public/index.html
- playgrounds/javascript/src/app.js
- playgrounds/react/src/App.js
- playgrounds/vue/src/App.vue
With the upgrade of versions in the [integration Meilisearch instance](https://integration-demos.meilisearch.com) the keys have been regenerated and thus are not working anymore.
This time the key has been created with a specific uid. On next updates of the Meilisearch server instead of changing the API key we just need to recreate the key in the new instance and the key will still be working.
> Update search key in playgrounds

- .github/scripts/check-tag-format.sh
- .github/workflows/publish.yml
- CONTRIBUTING.md
To be able to create beta releases on different subjects: `bumps`, `features`, etc.. we needed to provide a better suited CI.
This CI also checks if the tag well formated to ensure we do not publish a version that does not follow the naming convention.
The workflow has been tested on a private directory and seems to work correctly.
> Create new publish CI for beta versions

- src/cache/search-cache.ts
- src/client/instant-meilisearch-client.ts
- src/types/types.ts
Fixes [#790](https://github.com/meilisearch/instant-meilisearch/issues/790)
Implements clearCache method on InstantMeiliSearchInstance to allow realtime updates to search results. This allows algolias refresh example to work out of the box. ([https://www.algolia.com/doc/guides/building-search-ui/going-further/improve-performance/vue/#caching](https://www.algolia.com/doc/guides/building-search-ui/going-further/improve-performance/vue/#caching))
- [X ] Does this PR fix an existing issue?
- [X ] Have you read the contributing guidelines?
- [X ] Have you made sure that the title is accurate and descriptive of the changes?
> Add ability to clear cache to allow real-time refresh of search results.

- src/adapter/search-request-adapter/search-params-adapter.ts
In an effort to make a more maintainable code the huge function creating the search parameters is replaced by a more modular object creator.
It is made based on the adapter pattern see [refactoring guru](https://refactoring.guru/design-patterns/adapter/typescript/example). With a somewhat similar example in javascript [here](https://www.dottedsquirrel.com/adapter-pattern-javascript/)
> Object constructor for search parameters

- .github/workflows/beta-tests.yml
Missed the correct docker fetch in the second part of the beta tests
> Add correct docker image fetch in beta CI

- .github/workflows/beta-tests.yml
- .github/workflows/pre-release-tests.yml
- .github/workflows/publish.yml
- .github/workflows/tests.yml
- bors.toml
- package.json
- yarn.lock
- Add node 18 compatibility
- Add possibility to change meilisearch version in Cypress CI
- Use context for the meilisearch version
- Update all github actions to their latest version
> Update CI to latest versions of dependencies

- .github/workflows/beta-tests.yml
- .github/workflows/pre-release-tests.yml
- .github/workflows/tests.yml
- bors.toml
- Adds consistency in tests naming accross repo's
- Adds context / needs and services to access Meilisearch instance
> Fix naming and beta CI

- .github/workflows/publish.yml
- README.md
Fixes the node js compatibility in readme
and make publishing use node 16
> Update nodeJs requirements in readme and CI

- CONTRIBUTING.md
The beta guide was wrongly telling the user to create a specific formated branch which is not the one required.
> Update beta guide in contributing

- src/types/types.ts
the type `ClientParams` was used nowhere and added a useless complexity to the types.
`paginationTotalHits` is not added in the `SearchContext` as it is added in, and used from the `PaginationContext` 
Types are also re-ordered in order to get the mandatory fields at the top and the optional after them
> Remove unecessary clientParams type

- README.md
- src/adapter/search-request-adapter/__tests__/search-params.tests.ts
- src/adapter/search-request-adapter/search-params-adapter.ts
- src/contexts/search-context.ts
- src/types/types.ts
Introduces `optionalWords` search parameter.
It lets you decide the search strategy for words matching during a search.
`matchingStrategy` gives you the possibility to chose how Meilisearch should handle the presence of multiple query words.
For example, if your query is `Hello world` by default Meilisearch returns documents containing either both `Hello` and `world` or documents that only contain `hello`. This is the `last` strategy, where words are stripped from the right.
The other strategy is `all`, where both `hello` and `worlds` **must** be present in a document for it to be returned.
```js
import { instantMeiliSearch } from '@meilisearch/instant-meilisearch'
const searchClient = instantMeiliSearch(
host,
apiKey,
{
matchingStrategy: 'all' // default last
}
)
```
> Update search parameters for v0.29.0

- package.json
- src/package-version.ts
This version makes this package compatible with Meilisearch v0.29.0 :tada:
Check out the changelog of [Meilisearch v0.29.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.29.0) for more information on the changes.
- New Meilisearch option `matchingStrategy` #832
This breaking change *__may not affect you__*, but in any case, you should check your search queries if you want to keep the same behavior from `v0.28`.
- The `NOT` filter keyword does not have an implicitly `EXIST` operator anymore. Check out for more information: https://github.com/meilisearch/meilisearch/issues/2486
> Update version for the next release (v0.9.0)

- README.md
https://docs.meilisearch.com/reference/api/settings.html#update-ranking-rules documents that `desc` is the keyword for descending order
- Update readme example of descending sortBy widget
> fix: readme sortBy widget example

- package.json
- src/package-version.ts
This version makes this package compatible with Meilisearch v0.30.0 :tada:
Check out the changelog of [Meilisearch v0.30.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.30.0) for more information on the changes.
- `paginationTotalHits` does not exist anymore #878 
- `finitePagination` is now showcasing the exact number of pages based on the total number of document matched. #878
> Update version for the next release (v0.10.0)

- playgrounds/angular/src/app/app.component.ts
- playgrounds/geo-javascript/src/app.js
- playgrounds/html/public/index.html
- playgrounds/javascript/src/app.js
- playgrounds/react/src/App.js
- playgrounds/vue/src/App.vue
Integration instances, steam-games and world_cities are now hosted on the [cloud of meilisearch](https://cloud.meilisearch.com).
This required changing credentials with the new host and API key.
> Update playground instances to new instance on the cloud

- src/adapter/search-response-adapter/__tests__/geo-adapter.tests.ts
- src/adapter/search-response-adapter/geo-reponse-adapter.ts
Instantsearch geo widget requires the geo field to be named `_geoloc`. Nonetheless, the field returned from meilisearch is `_geo`. 
Previously we replaced `_geo` with `_geoloc` at the root of the hits (so not in `_formatted`) which in itself was a bug.
Since `instantsearch` needs `_geoloc` but we also want to avoid confusing the user to why their `_geo` field disappeared, we decided to keep both `_geo` and `_geoloc` files at the root of the hit but also in _formatted (of course only if there was a `_geo` field present to begin with).
> Keep both _geo and _geoloc fields in hits and hits._formatted

- src/adapter/search-request-adapter/__tests__/search-params.tests.ts
- src/adapter/search-request-adapter/search-params-adapter.ts
- src/adapter/search-request-adapter/search-resolver.ts
- src/types/types.ts
- tests/placeholder-search.tests.ts
`placeholderSearch` lets you enable (default) or disable the rendering of the hits when an empty search is made.
An empty search is a search without any query and without any filters.
When `placeholderSearch` was set to false, hits did not render when a filter was required.
When `placeholderSearch` was set to false, the pagination was rendered of is placeholder search was set to true.
With this PR:
- When placeholderSearch is set to false, If you add a filter, by clicking on a facet for example, hits are rendered
- When placeholderSearch is set to false, when the query and the filters are empty, the pagination does not render any page. 
- In finitePagination this is what is rendered:
- in scroll pagination: the load more button is disabled
> Multi-index search: fix placeholdersearch not working properly with filters and pagination

- playgrounds/vue3-ts/package.json
- playgrounds/vue3-ts/src/types/shims-vue.d.ts
the `vue` playground could not be build because of missing type files not related to instant-meilisearch. This PR adds a work-arround to ignore the issue.
> Fix building fail in @meilisearch/vue-playground

- .github/workflows/meilisearch-prototype-tests.yml
- .github/workflows/pre-release-tests.yml
The way we trigger tests were changed, see #953. While they were updated in the `tests.yml` CI file, they also needed to be updated in the pre-release and beta CI's
> Update the way we trigger tests in CI's

- .github/workflows/dependabot-auto-merge.yml
To avoid having to manually merge patches version updates opened by dependabot, this PR adds a github actions that automatically merges them.
> Automerge dependencies with a patch updage from dependabot

- CONTRIBUTING.md
- README.md
- packages/instant-meilisearch/CONTRIBUTING.md
- packages/instant-meilisearch/README.md
As the repository is now a mono-repo, the contributing guide had to be updated accordingly
> Update README's and CONTRIBUTING guides

- README.md
- package.json
- packages/instant-meilisearch/package.json
While it was initially planned to transform this repository into a repo containing multiple different types of plugins, we don't want to make this changes until it makes sense.
Currently the repo only holds the plugin of instant-meilisearch. When it will hold other plugins, for example #971, we will change the repository name.
> Keep instant-meilisearch as root readme until repo holds multiple plugins

- .github/workflows/publish.yml
- package.json
The initial idea was that every pre-release should be published under the dist tag `beta` tag in `npm` (see [tag tab in npm](https://www.npmjs.com/package/@meilisearch/instant-meilisearch?activeTab=versions)).
Unfortunately, it appears that when publishing a pre-release, `changesets` add a condition where we cannot add a custom tag. See issue https://github.com/changesets/changesets/issues/1037
Thus, the new way of doing it is to let changeset create a npm dist tag named after the pre-release version, in our case: `turbo-migration`. Once we consider this tag not to be relevant anymore, we can remove it from npm using [`npm-dist-tag`](https://docs.npmjs.com/cli/v9/commands/npm-dist-tag). 
Thus, every once in a while, a cleanup will be done to remove old tags that are not relevant anymore …
> Remove beta release process in publish CI

- .github/workflows/publish.yml
As per the doc of the changesets github action (see [here](https://github.com/changesets/action#with-publishing)
> By default the GitHub Action creates a .npmrc file with the following content:
>
> //registry.npmjs.org/:_authToken=${process.env.NPM_TOKEN}
> However, if a .npmrc file is found, the GitHub Action does not recreate the file. This is useful if you need to configure the .npmrc file on your own. For example, you can add a step before running the Changesets GitHub Action:
We need to add an additional step to create the `npmrc` at the root of the repo during the publish action.
> Create required npmrc file upon publishing packages

- .github/workflows/publish.yml
After having the CI fail again, one of the possibilities of fixing this issue is suggested by this user in this [comment](https://github.com/changesets/action/issues/98#issuecomment-917292485).
Another possibility is that `actions/setup-node@v3` also creates a npmrc that requires a `NPM_AUTH_TOKEN` see [doc](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry)
This PR's commit is bound to be removed from #939 and is there for trying purposes.
> Explicitely provide a NODE_AUTH_TOKEN in the publish CI

- .changeset/pre.json
Since #939 has been released in pre-release mode and then pushed to main, we now need to exit pre-release mode.
As per [the documentation](https://github.com/changesets/changesets/blob/main/docs/prereleases.md)
> Exit pre-release mode for next release

- .github/workflows/pre-release-tests.yml
When a push occurs on a branch pointing to a bump branch, the `push` action does not trigger as it does not match the required branch patterns. When a pull_request activity on a bump branch occurs, the pre-release tests were triggered but because of the wrong if condition, the jobs were not executed.
The if condition should ensure that the base branch corresponds to the pull_request branch patterns.
Which is now the case
> Fix pre-release CI not triggering

- .changeset/red-fans-cross.md
- README.md
- packages/instant-meilisearch/__tests__/sort.test.ts
- packages/instant-meilisearch/src/adapter/search-request-adapter/search-params-adapter.ts
- packages/instant-meilisearch/src/contexts/search-context.ts
- packages/instant-meilisearch/src/contexts/sort-context.ts
- packages/instant-meilisearch/src/types/types.ts
I created a new pull request with changes that @bidoubiwa requested in pull request  #1024.
Fixes #539
> Add support for multiple sort attributes

- .changeset/perfect-dodos-call.md
- package.json
- packages/instant-meilisearch/rollup.config.js
- playgrounds/node-env/index.js
- playgrounds/node-env/package.json
the `umd` build of this package was missing the polyfill of `fetch`. Resulting in the following being thrown
```
XMLHttpRequest is not defined
```
As the package tries to use the browser `fetch` API.
Fixes: #1061
> Make umd build compatible in a node environment

- .github/workflows/tests.yml
- package.json
- playgrounds/node-env/package.json
The build command in the node playground was run whenever the release was triggered. But in reality the node playground does not need to be built, it rather runs a script to see if it can interact correctly with instant meilisearch.
This PR changes the command from build to dev so that turbo build does not trigger it. It also adds a line in the test ci to ensure the script runs correctly
> Change the cmd to run the script in the node-playground

- .changeset/tender-dancers-check.md
- packages/instant-meilisearch/src/adapter/search-request-adapter/__tests__/search-params.test.ts
- packages/instant-meilisearch/src/adapter/search-request-adapter/filter-adapter.ts
- packages/instant-meilisearch/src/utils/string.ts
fixes: #1083 
Facets containing multiple words, for example `In stock`, were wrongly formatted. Meilisearch requires multi-words in filters to be wrapped in double quotes. The solution provided is to wrap every facet attribute and facet value in double quotes.
Before:
'In stock="value"'
After
'"In stock"="value"'
> Fix multi words filters not formatted correctly

- .github/workflows/meilisearch-prototype-tests.yml
- .github/workflows/pre-release-tests.yml
- .github/workflows/publish.yml
- .github/workflows/tests.yml
Fixes #1119 
Upgrade node version in CI workflows (from node 16 to node 18) in following files:
- .github/workflows/meilisearch-prototype-tests.yml
- .github/workflows/pre-release-tests.yml
- .github/workflows/publish.yml
- .github/workflows/tests.yml
> Upgrade node version in CI workflows

- packages/instant-meilisearch/__tests__/snippets.test.ts
- packages/instant-meilisearch/package.json
- yarn.lock
Update meilisearch-js to v0.33.0 and fix a failing tests introduced by the new version of Meilisearch (the engine) v1.2.0.
This failing test is due to a change in the way the cropping is processed on Meilisearch sides and is considered not a breaking change.
The test was changed to be more robust.
> Update meilisearch js to v0.33.0

- packages/autocomplete-client/package.json
the autocomplete-client was added to npm as a private package, making it impossible to access without the writes on the package.
> Make autocomplete public on npm

- .github/workflows/publish.yml
Missing wildcards resulted in the publishing CI not triggering on prototype versions.
> Fix the publish CI not running on a prototype

- .changeset/dirty-mangos-tie.md
- packages/instant-meilisearch/__tests__/sort.test.ts
- packages/instant-meilisearch/src/contexts/search-context.ts
- packages/instant-meilisearch/src/contexts/sort-context.ts
Fixes: #1159 
The old implementation did not take into account that a sorting rule could contain the `,` character and naively splited on that char.
Which resulted in 
```
"indexName:_geoPoint(37.8153, -122.4784):asc"
```
Being transformed into:
```
[
"indexName:_geoPoint(37.8153",
"-122.4784):asc"
]
```
Instead of splitting solely on `,`, we now split on a coma if it is prepended by `asc` or `desc`.
> Fix bug when sort-by contains geo points

- .changeset/green-bottles-sing.md
- packages/instant-meilisearch/src/client/instant-meilisearch-client.ts
- packages/instant-meilisearch/src/contexts/search-context.ts
- playgrounds/local-react/cypress/integration/search-ui.spec.js
Fixes #1222
Fixes a bug where, when you use the sort by widget and changes the default sorting by another one, the facet search would break.
The issue was that when sorting the name of the indexUid is formatted like this `indexName:attribute:sortOrder`, and instead of using only the `indexName` part to do the search request, it was using the whole string.
> Fix facet search when using sortBy

- .github/dependabot.yml
To avoid being spammed with none-critical dependencies updates suggested by dependabot, we are changing from `ignore` to `allow` in the dependabot file. Ensuring we only update the critical dependencies.
```
- dependency-name: meilisearch
```
meilisearch is kept as it is the only one that is builded with the package. Updates of this library ensure that the library includes all new features provided by meilisearch-js.
> Update dependabot changing ignore list to allow list

- .changeset/three-pandas-chew.md
- packages/instant-meilisearch/__tests__/assets/utils.ts
- packages/instant-meilisearch/__tests__/filter.test.ts
- packages/instant-meilisearch/src/adapter/search-request-adapter/filter-adapter.ts
Fixes #1256
- Fixes issue where backslashes ("\\") and quotes (`"`) are not escaped in filters
- Also numeric filter attributes are now always wrapped in quotes
> Escape filter backslashes and quotes

- .changeset/metal-emus-pump.md
- .code-samples.meilisearch.yaml
- packages/autocomplete-client/src/client/createSearchClient.ts
- packages/instant-meilisearch/README.md
- packages/instant-meilisearch/__tests__/assets/utils.ts
- packages/instant-meilisearch/__tests__/custom-http-client.test.ts
- packages/instant-meilisearch/__tests__/disjunctive-facet-search.test.ts
- packages/instant-meilisearch/__tests__/first-facets-distribution.test.ts
- packages/instant-meilisearch/__tests__/multi-index-search.test.ts
- packages/instant-meilisearch/__tests__/overridden-meilisearch-parameters.test.ts
- packages/instant-meilisearch/__tests__/placeholder-search.test.ts
- packages/instant-meilisearch/__tests__/search-resolver.test.ts
- packages/instant-meilisearch/src/adapter/search-request-adapter/__tests__/search-params.test.ts
- packages/instant-meilisearch/src/adapter/search-request-adapter/search-params-adapter.ts
- packages/instant-meilisearch/src/cache/init-facets-distribution.ts
- packages/instant-meilisearch/src/client/config/index.ts
- packages/instant-meilisearch/src/client/instant-meilisearch-client.ts
- packages/instant-meilisearch/src/types/types.ts
- playgrounds/angular/src/app/app.component.ts
- playgrounds/geo-javascript/src/app.js
- playgrounds/javascript/src/app.js
- playgrounds/local-react/src/components/MultiIndex.jsx
- playgrounds/local-react/src/components/SingleIndex.jsx
- playgrounds/local-react/src/components/SingleMovieIndex.jsx
- playgrounds/node-env/index.js
- playgrounds/react/src/App.jsx
- playgrounds/vue3-ts/src/App.vue
Fixes #1249 
- Adds ability to configure and override a selection of Meilisearch search parameters
- Modifies some types, stronger type checking
> Expose a set of Meilisearch search parameters to be overridden/configured

- .changeset/fluffy-waves-love.md
- packages/instant-meilisearch/README.md
- packages/instant-meilisearch/src/adapter/search-request-adapter/__tests__/search-params.test.ts
- packages/instant-meilisearch/src/adapter/search-request-adapter/search-params-adapter.ts
- packages/instant-meilisearch/src/client/instant-meilisearch-client.ts
- packages/instant-meilisearch/src/types/types.ts
Hi 👋 this PR enables using the [hybrid search](https://www.meilisearch.com/docs/learn/experimental/vector_search#vector-search-with-auto-embeddings) experimental API with `@meilisearch/instant-meilisearch`.
Solves #1286 
Allow users to pass a `hybrid` object in the `meiliSearchParams` object when creating an instantMeilisearch client.
```js
instantMeiliSearch(host, apiKey, {
primaryKey: 'id',
meiliSearchParams: {
// other meilisearch params
hybrid: {
semanticRatio: 0.9,
embedder: 'default',
},
},
})
```
Additionally, the `adaptSearchParams` function will now internally handle this `hybrid` object.
- Add `hybrid` object as an overridable search parameter
> InstantMeilisearch: Enable hybrid search

- .changeset/beige-peaches-divide.md
- .github/workflows/meilisearch-prototype-tests.yml
- .github/workflows/pre-release-tests.yml
- .github/workflows/tests.yml
- bors.toml
- packages/autocomplete-client/README.md
Node 14 and 16 are EOL now so we can remove them from our CI and adopt the new LTS node.js v20.
> Remove node 14 and 16 from workflow

- .changeset/sharp-ways-argue.md
- packages/instant-meilisearch/src/adapter/search-response-adapter/__tests__/hit-adapter.test.ts
- packages/instant-meilisearch/src/adapter/search-response-adapter/hits-adapter.ts
Fixes #1305
Corrects _matchesPosition field not being included in each hit when meiliSearchParam.showMatchesPosition=true
This bug was introduced in PR #739, release [0.7.1](https://github.com/meilisearch/meilisearch-js-plugins/releases/tag/v0.7.1), which just seems to have been a typo/forgetting to include _matchesPosition, as you can see it was included in the destructured assignment, but not used.
> instant-meilisearch: Fix _matchesPosition not being included in hits

- .changeset/sharp-ways-argue.md
- packages/instant-meilisearch/CHANGELOG.md
- packages/instant-meilisearch/package.json
- packages/instant-meilisearch/src/package-version.ts
- playgrounds/angular/package.json
- playgrounds/geo-javascript/package.json
- playgrounds/javascript/package.json
- playgrounds/local-react/package.json
- playgrounds/react/package.json
- playgrounds/vue3-ts/package.json
Related to https://github.com/meilisearch/meilisearch-js-plugins/pull/1307
The CI was not being triggered in that PR.
> Version Packages

- packages/instant-meilisearch/__tests__/overridden-meilisearch-parameters.test.ts
Fixes #1340 
- Update tests on results highlights to follow new formatting
> Update highlighting tests

- packages/autocomplete-client/README.md
This PR:
- Removes documentation about `matchingStrategy` field in `options` (does not exist)
- Removes the section about Matching Strategy for consistency
Follows an incomplete update of documentation made in #1343, and actually fixes #1338
Thanks to @sgilberg for the report and review 🙌
> Update `matchingStrategy` docs in autocomplete client README

- .changeset/silly-badgers-hug.md
- packages/autocomplete-client/__tests__/test.utils.ts
- packages/autocomplete-client/src/search/__tests__/fetchMeilisearchResults.test.ts
- packages/autocomplete-client/src/search/fetchMeilisearchResults.ts
Fixes #1337
This PR enriches the `_highlightResult` object with metadata:
- `fullyHighlighted`:  whether the highlighted text covers the entire field
- `matchLevel`: degree of the match (none, partial, or full)
- `matchedWords`: array of words matched
While adding the necessary tests, I also improved the existing tests for `fetchMeilisearchResults.ts`.
> Add highlight metadata to autocomplete client

- .changeset/strong-dodos-carry.md
- packages/instant-meilisearch/src/adapter/search-request-adapter/__tests__/search-params.test.ts
- packages/instant-meilisearch/src/adapter/search-request-adapter/search-params-adapter.ts
- packages/instant-meilisearch/src/types/types.ts
Fixes #1351
Add vector search param to support vector search with user-provided embedding
> Add vector search param
